/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface OrderAndChaos {
    'address': string;
  }
}

declare global {


  interface HTMLOrderAndChaosElement extends Components.OrderAndChaos, HTMLStencilElement {}
  var HTMLOrderAndChaosElement: {
    prototype: HTMLOrderAndChaosElement;
    new (): HTMLOrderAndChaosElement;
  };
  interface HTMLElementTagNameMap {
    'order-and-chaos': HTMLOrderAndChaosElement;
  }
}

declare namespace LocalJSX {
  interface OrderAndChaos {
    'address'?: string;
  }

  interface IntrinsicElements {
    'order-and-chaos': OrderAndChaos;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'order-and-chaos': LocalJSX.OrderAndChaos & JSXBase.HTMLAttributes<HTMLOrderAndChaosElement>;
    }
  }
}


